---
language: ruby
bundler_args: --without development

env:
  secure: "gMvIYh5U4Z8Cr2rxrSZItWhkRqTtHXNpB7q9KmbtVFplLY5vz6RWY+tJWOg2y8Y71XpjYQMBy5Y00f8ZcoRm3NJ9Po9+S5uHglPSMg82mw1zClPGKGm7vrL8QT6qCkCx0L4dIuenb540hZ9eDs+xvHAfXk4vcez/SEWfi/c2Kvg="

notifications:
  slack: TRAVIS_KEY

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install bundler -v 1.10.6

before_script:
  - bundle exec rake db:setup

after_success:
  - ./script/deploy-staging.sh


