---
language: ruby
bundler_args: --without development

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install bundler -v 1.10.6

before_script:
  - bundle exec rake db:setup

after_success:
  - ./script/deploy-staging.sh


