language: ruby
bundler_args: "--without development"
addons:
  code_climate:
    repo_token:
      secure: VTel8SABYIABU98M/ki2PesW7HLogE+RJFEo1jbKnB2brHtPM/lPo04JBvGCiL/BZ9KdIgUF/NN8ylM+cR7LBq9xPDcnw00H82OS5A2lweBo9a+pQys6E8F3eYDSRGY3+KdHlmG6nlnqMwRWBRySinyYH+erpXd7mQm8ZrUlfgE=
notifications:
  slack:
    rooms:
      secure: uKhA3tvH4WiQyRoRpoIsce4i7fYiK3udeGBOOpGbUPxw99uYlc+Go6jx0bWCsRT4sMpboNOAig6A/n+B36gJGFgwMKnxc4pKWSD+68A9yoRHMg3ekur0jP3p+y6Phka4UBF67B4eulPknV2MwHaS8wK3vQE/Gd7xeqa+2JnDTZQ=
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install bundler -v 1.10.6
before_script:
- bundle exec rake db:setup
after_success:
- "./script/deploy-staging.sh"
