sudo: true
language: ruby
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "gem install bundler -v 1.10.6"
script: "RAILS_ENV=test bundle exec rake db:create db:migrate default"
after_success: ./script/deploy-staging.sh
bundler_args: --without development
