---
applications:
- name: whiteboard-acceptance
  no-route: true
  command: bundle exec rake db:create db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb
  services:
    - whiteboard-acceptance-db
